from aiogram.dispatcher.filters.state import State, StatesGroup


class GoStates(StatesGroup):
    address = State()
    apply = State()
    ban = State()
    bank_name = State()
    bank_zero = State()
    btc = State()
    byn = State()
    delete_user = State()
    everybody_users = State()
    everybody_users_coin = State()
    everybody_users_choice = State()
    fees = State()
    fees_for_crypto = State()
    go = State()
    is_only_day = State()
    max_amount = State()
    max_amount_for_crypto = State()
    min_amount = State()
    min_amount_for_crypto = State()
    notification = State()
    pay = State()
    percent = State()
    percent_for_crypto = State()
    photo = State()
    photo_ok = State()
    start = State()
    setting = State()
    turn_off = State()
    turn_off_btc = State()
    rate = State()
    rate_for_crypto = State()

    rate_btc_usdt = State()
    rate_btc_usdt_calculate_btc = State()
    rate_btc_usdt_calculate_usdt = State()
    
    remove_requisiters_bank = State()
    requisiters = State()
    usd = State()
    usd_byn = State()
    usdt = State()
    usdt_byn = State()
    user_registred = State()
    wait = State()
    wait_approve = State()
